name: Check Format

on: push

jobs:
  check-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install clang-format
      - name: Check format
        run: |
          make fmt
          git diff --exit-code
