name: Check Coverage

on: push

jobs:
  C1-50:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install lcov
      - name: Generate coverage report
        run: make coverage
      - name: Check if branch coverage is 50%
        run: |
          BRANCH_COVERAGE=$(cd ./test/build && lcov --summary coverage.filtered.info --rc "lcov_branch_coverage=1" | grep "branches" | awk '{print $2}' | tr -d '%')
          result=$(echo "$BRANCH_COVERAGE >= 50" | bc)
          if [ "$result" -eq 1 ]; then \
              echo "Branch coverage is sufficient: $BRANCH_COVERAGE%"
          else
              echo "Error: Branch coverage is below 50%: $BRANCH_COVERAGE%"
              exit 1
          fi
